apiVersion: certmanager.k8s.io/v1alpha2
kind: Certificate
metadata:
  name: birdboard-ml-tls
spec:
  secretName: birdboard-ml
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: birdboard.ml
  dnsNames:
    - birdboard.ml
    - www.birdboard.ml
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - birdboard.ml
          - www.birdboard.ml
